<?php
    /** @var Devils_Filters_Block_Layer_Filter_Price $this */
    $minPrice = $this->getMinPrice();
    $maxPrice = $this->getMaxPrice();
    $inputName = $this->getFilter()->getRequestVar();
    list($filterMinPrice, $filterMaxPrice) = $this->getRequestedRange($inputName);
?>
<dt>
    <?php echo $this->__($this->getName()); ?>:
    <span class="priceSlider-amountTag">
        <?php echo $filterMinPrice . ' - ' . $filterMaxPrice; ?>
    </span>
    <span class="priceSlider-currencyTag"></span>
</dt>
<dd>
    <ol>
        <input type="hidden" class="priceSlider-amount" name="<?php echo $inputName ?>"
               value="<?php echo $filterMinPrice . '-' . $filterMaxPrice?>">
        <div class="priceSlider-range"></div>
    </ol>

    <script>
        jQuery( document ).ready(function( $ ) {
            $('.priceSlider-range').slider({
                range: true,
                min: <?php echo $minPrice; ?>,
                max: <?php echo $maxPrice; ?>,
                values: [ <?php echo $filterMinPrice; ?>, <?php echo $filterMaxPrice; ?> ],
                slide: function( event, ui ) {
                    $('.priceSlider-amount').val(ui.values[ 0 ] + '-' + ui.values[ 1 ] );
                    $('.priceSlider-amountTag').html(ui.values[ 0 ] + ' - ' + ui.values[ 1 ] );
                }
            });
            $('.priceSlider-amount').val( $( '.priceSlider-range').slider( "values", 0 ) +
                "-" + $('.priceSlider-range').slider( "values", 1 ) );
        } );
    </script>
</dd>
