<ol>
    <?php foreach ($this->getItems() as $_item):
        $inputName = $_item->getFilter()->getRequestVar();
        $inputValue = $_item->getValue();
        $inputLabel = $_item->getLabel();
        $inputCount = $_item->getCount();
    ?>
        <li>
            <?php if ($_item->getCount() > 0): ?>
                <label>
                    <input type="checkbox"
                        <?php echo ($this->getIsSelected($inputName, $inputValue)) ? 'checked="checked"' : ''; ?>
                           name="<?php echo $inputName; ?>[]"
                           value="<?php echo $inputValue; ?>"> <?php echo $inputLabel; ?>
                    <?php if ($this->shouldDisplayProductCount()): ?>
                        (<?php echo $inputCount; ?>)
                    <?php endif; ?>
                </label>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
